const repository = 'Mentornoob/QLTV-Updates';
function formatDate(value){if(!value)return '';const date=new Date(value.length===10?value+'T00:00:00Z':value);return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}).format(date)}
function bodyNotes(body){return(body||'').split('\n').map(function(line){return line.replace(/^[-*•]\s*/,'').replace(/^#+\s*/,'').trim()}).filter(function(line){return line&&!/^https?:\/\//.test(line)}).slice(0,5)}
function updatePage(release){
 const version=release.version||(release.tag_name||'').replace(/^v/,'');const title=release.title||release.name||'QLTV '+version;const date=release.release_date||release.published_at;const notes=release.notes||bodyNotes(release.body);const assets=release.assets||[];const installer=assets.find(function(asset){return asset.name.toLowerCase().endsWith('.exe')});const checksum=assets.find(function(asset){return asset.name.toLowerCase().endsWith('.sha256')});const downloadUrl=release.download_url||(installer&&installer.browser_download_url)||release.html_url;const checksumUrl=release.checksum_url||(checksum&&checksum.browser_download_url);
 document.querySelectorAll('.latest-version').forEach(function(element){element.textContent='v'+version});document.querySelectorAll('.latest-date').forEach(function(element){element.textContent=formatDate(date)});document.querySelectorAll('.download-link').forEach(function(element){if(downloadUrl)element.href=downloadUrl});document.querySelector('.latest-title').textContent=title;
 if(notes&&notes.length){const list=document.querySelector('.latest-notes');list.replaceChildren();notes.forEach(function(note){const item=document.createElement('li');item.textContent=note;list.appendChild(item)})}if(checksumUrl)document.querySelector('.checksum-link').href=checksumUrl
}
function renderHistory(releases){const container=document.querySelector('#release-history');container.replaceChildren();releases.slice(1,6).forEach(function(release){const item=document.createElement('article');const link=document.createElement('a');const version=document.createElement('b');const date=document.createElement('span');link.href=release.html_url;link.target='_blank';link.rel='noopener noreferrer';version.textContent=release.tag_name;date.textContent=formatDate(release.published_at);link.appendChild(version);item.append(link,date);container.appendChild(item)});if(!container.children.length)container.textContent='Chưa có bản phát hành trước đó.'}
async function loadData(){try{const response=await fetch('update.json',{cache:'no-store'});if(!response.ok)throw new Error('Không thể tải update.json');updatePage(await response.json())}catch(error){console.warn(error.message)}try{const response=await fetch('https://api.github.com/repos/'+repository+'/releases?per_page=6',{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error('Không thể tải lịch sử phát hành');renderHistory(await response.json())}catch(error){console.warn(error.message);document.querySelector('#release-history').textContent='Xem lịch sử đầy đủ trên GitHub Releases.'}}
function initMenu(){const button=document.querySelector('.menu');const navigation=document.querySelector('.nav nav');button.addEventListener('click',function(){const open=navigation.classList.toggle('open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Đóng menu':'Mở menu')});navigation.querySelectorAll('a').forEach(function(link){link.addEventListener('click',function(){navigation.classList.remove('open');button.setAttribute('aria-expanded','false')})})}
function initReveal(){const elements=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){elements.forEach(function(element){element.classList.add('visible')});return}const observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.12});elements.forEach(function(element){observer.observe(element)})}
document.querySelector('#year').textContent=new Date().getFullYear();initMenu();initReveal();loadData();