const repository = 'Mentornoob/QLTV-Updates';
function formatDate(value){if(!value)return '';const date=new Date(value.length===10?value+'T00:00:00Z':value);return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}).format(date)}
function bodyNotes(body){return(body||'').split('\n').map(function(line){return line.replace(/^[-*•]\s*/,'').replace(/^#+\s*/,'').trim()}).filter(function(line){return line&&!/^https?:\/\//.test(line)}).slice(0,5)}
function updatePage(release){
 const version=release.version||(release.tag_name||'').replace(/^v/,'');const title=release.title||release.name||'QLTV '+version;const date=release.release_date||release.published_at;const notes=release.notes||bodyNotes(release.body);const assets=release.assets||[];const installer=assets.find(function(asset){return asset.name.toLowerCase().endsWith('.exe')});const checksum=assets.find(function(asset){return asset.name.toLowerCase().endsWith('.sha256')});const downloadUrl=release.download_url||(installer&&installer.browser_download_url)||release.html_url;const checksumUrl=release.checksum_url||(checksum&&checksum.browser_download_url);
 document.querySelectorAll('.latest-version').forEach(function(element){element.textContent='v'+version});document.querySelectorAll('.latest-date').forEach(function(element){element.textContent=formatDate(date)});document.querySelectorAll('.download-link').forEach(function(element){if(downloadUrl)element.href=downloadUrl});document.querySelector('.latest-title').textContent=title;
 if(notes&&notes.length){const list=document.querySelector('.latest-notes');list.replaceChildren();notes.forEach(function(note){const item=document.createElement('li');item.textContent=note;list.appendChild(item)})}if(checksumUrl)document.querySelectorAll('.checksum-link').forEach(function(element){element.href=checksumUrl})
}
function renderHistory(releases){const container=document.querySelector('#release-history');container.replaceChildren();releases.slice(1,6).forEach(function(release){const item=document.createElement('article');const link=document.createElement('a');const version=document.createElement('b');const date=document.createElement('span');link.href=release.html_url;link.target='_blank';link.rel='noopener noreferrer';version.textContent=release.tag_name;date.textContent=formatDate(release.published_at);link.appendChild(version);item.append(link,date);container.appendChild(item)});if(!container.children.length)container.textContent='Chưa có bản phát hành trước đó.'}
async function loadData(){try{const response=await fetch('update.json',{cache:'no-store'});if(!response.ok)throw new Error('Không thể tải update.json');updatePage(await response.json())}catch(error){console.warn(error.message)}try{const response=await fetch('https://api.github.com/repos/'+repository+'/releases?per_page=6',{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error('Không thể tải lịch sử phát hành');renderHistory(await response.json())}catch(error){console.warn(error.message);document.querySelector('#release-history').textContent='Xem lịch sử đầy đủ trên GitHub Releases.'}}
function initMenu(){const button=document.querySelector('.menu');const navigation=document.querySelector('.nav nav');button.addEventListener('click',function(){const open=navigation.classList.toggle('open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Đóng menu':'Mở menu')});navigation.querySelectorAll('a').forEach(function(link){link.addEventListener('click',function(){navigation.classList.remove('open');button.setAttribute('aria-expanded','false')})})}
function initReveal(){const elements=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){elements.forEach(function(element){element.classList.add('visible')});return}const observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.12});elements.forEach(function(element){observer.observe(element)})}
function initShowcase(){
 const root=document.querySelector('[data-showcase]');if(!root)return;
 const slides=Array.from(root.querySelectorAll('.showcase-slide'));const dots=Array.from(root.querySelectorAll('[data-showcase-dot]'));const title=root.querySelector('[data-showcase-title]');const previous=root.querySelector('[data-showcase-prev]');const next=root.querySelector('[data-showcase-next]');
 if(!slides.length)return;
 const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;let active=0;let timer=null;
 function show(index){active=(index+slides.length)%slides.length;slides.forEach(function(slide,slideIndex){const selected=slideIndex===active;slide.classList.toggle('is-active',selected);slide.setAttribute('aria-hidden',String(!selected))});dots.forEach(function(dot,dotIndex){const selected=dotIndex===active;dot.classList.toggle('is-active',selected);dot.setAttribute('aria-selected',String(selected))});if(title)title.textContent=slides[active].dataset.title||''}
 function stop(){if(timer!==null){window.clearInterval(timer);timer=null}}
 function start(){stop();if(!reduceMotion&&!document.hidden)timer=window.setInterval(function(){show(active+1)},3200)}
 if(previous)previous.addEventListener('click',function(){show(active-1);start()});if(next)next.addEventListener('click',function(){show(active+1);start()});dots.forEach(function(dot,index){dot.addEventListener('click',function(){show(index);start()})});
 root.querySelectorAll('[data-compare]').forEach(function(compare){
  let dragging=false;
  function setSplit(value){const split=Math.max(5,Math.min(95,Math.round(value*10)/10));compare.style.setProperty('--split',split+'%');compare.setAttribute('aria-valuenow',String(Math.round(split)));compare.setAttribute('aria-valuetext',Math.round(split)+'% giao diện sáng, '+Math.round(100-split)+'% giao diện tối')}
  function setFromPointer(clientX){const rect=compare.getBoundingClientRect();if(rect.width)setSplit((clientX-rect.left)/rect.width*100)}
  function finish(event){if(!dragging)return;dragging=false;compare.classList.remove('is-dragging');if(event&&compare.hasPointerCapture&&compare.hasPointerCapture(event.pointerId))compare.releasePointerCapture(event.pointerId);start()}
  compare.addEventListener('pointerdown',function(event){if(event.pointerType==='mouse'&&event.button!==0)return;dragging=true;compare.classList.add('is-dragging');compare.focus({preventScroll:true});compare.setPointerCapture(event.pointerId);setFromPointer(event.clientX);stop();event.preventDefault()});
  compare.addEventListener('pointermove',function(event){if(dragging)setFromPointer(event.clientX)});
  compare.addEventListener('pointerup',finish);compare.addEventListener('pointercancel',finish);
  compare.addEventListener('keydown',function(event){let value=Number(compare.getAttribute('aria-valuenow'))||50;let handled=true;if(event.key==='ArrowLeft'||event.key==='ArrowDown')value-=3;else if(event.key==='ArrowRight'||event.key==='ArrowUp')value+=3;else if(event.key==='Home')value=5;else if(event.key==='End')value=95;else handled=false;if(handled){event.preventDefault();event.stopPropagation();setSplit(value)}});
  compare.addEventListener('dblclick',function(){setSplit(50)});setSplit(50)
 });
 root.addEventListener('mouseenter',stop);root.addEventListener('mouseleave',start);root.addEventListener('focusin',stop);root.addEventListener('focusout',function(event){if(!root.contains(event.relatedTarget))start()});
 root.addEventListener('keydown',function(event){if(event.target.closest('[data-compare]'))return;if(event.key==='ArrowLeft'){event.preventDefault();show(active-1);start()}else if(event.key==='ArrowRight'){event.preventDefault();show(active+1);start()}});
 document.addEventListener('visibilitychange',function(){if(document.hidden)stop();else start()});show(0);start()
}
document.querySelector('#year').textContent=new Date().getFullYear();initMenu();initReveal();initShowcase();loadData();